data:
  train_test_split_percent: 0.8
  sequence_length: 7
  batch_size: 32
  data_path: "data/A.csv"

model:
  hidden_dim: 64
  num_layers: 2
  dropout: 0
  input_size: 6
  model_type: "StockLSTM"  # Options: "StockLSTM" or "StockGRU"

training:
  epochs: 50
  learning_rate: 0.001
  patience: 5
  lr_factor: 0.5
  error: "MSE"
