[project]
name = "stockprediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "ruff>=0.14.1",
    "scikit-learn>=1.7.2",
    "torch>=2.8.0",
]
